package com.eirs.lsm.repository.entity;

public interface SystemConfigKeys {

    String LSM_NO_OF_OPERATORS = "LSM_NO_OF_OPERATORS";
    String LSM_OPERATOR = "LSM_OPERATORS_<NUMBER>";

    /**
     * Timer to start.
     */
    String PICK_DATE_BEFORE_TIME = "LSM_PICK_DATE_BEFORE_TIME";

    String FAILED_SYNC_RETRY_AFTER_MINUTES = "FAILED_SYNC_RETRY_AFTER_MINUTES";
    Integer DEFAULT_PICK_DATE_BEFORE_TIME = 6;

    /******** List last read date****/

    /****Enabling Feature keys****/

    String ENABLE_PROCESSING_BLACKED_LIST = "LSM_ENABLE_PROCESSING_BLACKED_LIST";

    String ENABLE_PROCESSING_BLOCKED_TAC = "LSM_ENABLE_PROCESSING_BLOCKED_TAC";

    String ENABLE_PROCESSING_ALLOWED_TAC = "LSM_ENABLE_PROCESSING_ALLOWED_TAC";

    String ENABLE_PROCESSING_TRACKED_LIST = "LSM_ENABLE_PROCESSING_TRACKED_LIST";

    String ENABLE_PROCESSING_EXCEPTION_LIST = "LSM_ENABLE_PROCESSING_EXCEPTION_LIST";


    /******** OPERATOR TPS *****/

    String OPERATOR_TPS = "LSM_<OPERATOR>_TPS";

    String OPERATOR_NO_OF_EIRS = "LSM_<OPERATOR>_NO_EIRS";

    Integer DEFAULT_OPERATOR_TPS = 50;

    String OPERATOR_URL_BASIC_AUTH_CREDENTIALS = "LSM_<OPERATOR>_BASIC_AUTH_CREDENTIALS";

    String OPERATOR_URL_READ_TIME_OUT = "LSM_<OPERATOR>_READ_TIME_OUT";

    String OPERATOR_URL = "LSM_<OPERATOR>_URL_<NUMBER>";
}
