spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eirs
    username: root
    password: ENC(jxNzi7e8T94AnHUxgizmuQ==)
    driverClassName: com.mysql.cj.jdbc.Driver
#  datasource:
#    url: jdbc:oracle:thin:@64.227.137.112:1521/ORCLPDB1
#    username: CRESTELCEIR
#    password: CRESTELCEIR123#
#    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: false
    #properties:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      dialect: org.hibernate.dialect.Oracle10gDialect


provision-gateway:
  certificate:
    key-store: classpath:dmc_eir.p12
    key-password: ENC(JM+vF0m1pHbWwTljIPg9sBzTy5YMye0v)

jasypt:
  encryptor:
    password: eir
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

alerts:
  postUrl: http://127.0.0.1:9504/eir/alert
  processId: ListSyncModule
  alerts-mapping:
    LIST_SYNC_URL_EXCEPTION:
      alertId: ALERT1001
      message: "Not able to call CORE Module,<OPERATOR> <URL> : <EXCEPTION>."
    DATABASE_EXCEPTION:
      alertId: ALERT2020
      message: "Database Exception, <LIST> : <EXCEPTION>."
    CONFIGURATION_VALUE_MISSING:
      alertId: ALERT2020
      message: "Missing value for Key: <CONFIG_KEY>."
    CONFIGURATION_VALUE_WRONG:
      alertId: ALERT2020
      message: "Wrong value for Key: <CONFIG_KEY> ConfiguredValue: <CONFIG_VALUE>"

deviceSyncRequest:
  delete:
    filePath: